/*
 * Biblio Librarian - Open API 3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Book struct {

	Title *Object `json:"title"`

	Authors []string `json:"authors"`

	Isbn []Isbn `json:"isbn"`

	Awards []string `json:"awards,omitempty"`

	Subjects []string `json:"subjects,omitempty"`

	Genres []string `json:"genres,omitempty"`
}
