/*
 * Biblio Librarian - Open API 3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"AuthorGet",
		strings.ToUpper("Get"),
		"/author",
		AuthorGet,
	},

	Route{
		"AwardGet",
		strings.ToUpper("Get"),
		"/award",
		AwardGet,
	},

	Route{
		"BookIsbnGet",
		strings.ToUpper("Get"),
		"/book/{isbn}",
		BookIsbnGet,
	},

	Route{
		"BookPost",
		strings.ToUpper("Post"),
		"/book",
		BookPost,
	},

	Route{
		"BookPut",
		strings.ToUpper("Put"),
		"/book",
		BookPut,
	},

	Route{
		"BooksGet",
		strings.ToUpper("Get"),
		"/books",
		BooksGet,
	},

	Route{
		"StatsGet",
		strings.ToUpper("Get"),
		"/stats",
		StatsGet,
	},

	Route{
		"SeriesGet",
		strings.ToUpper("Get"),
		"/series",
		SeriesGet,
	},

	Route{
		"SubjectsGet",
		strings.ToUpper("Get"),
		"/subjects",
		SubjectsGet,
	},
}
